In [ ]:
# Block 1: Imports and Setup

import os
import numpy as np
import pandas as pd

from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error

import tensorflow as tf
from tensorflow.keras import layers, models, callbacks, saving # Import saving module

import matplotlib.pyplot as plt
import joblib

# --- Configuration ---
INPUT_CSV_PATH = '/content/drive/MyDrive/AML /All/stockprice.csv'  # update if needed

# Output folders (created alongside the CSV)
BASE_DIR = os.path.dirname(os.path.abspath(INPUT_CSV_PATH))
OUTPUT_FIGURES_DIR = os.path.join(BASE_DIR, "figures_with_cluster")
OUTPUT_MODELS_DIR  = os.path.join(BASE_DIR, "models_1")
OUTPUT_RESULTS_DIR = os.path.join(BASE_DIR, "results_")
SCALERS_DIR        = os.path.join(OUTPUT_MODELS_DIR, "scalers_1")

os.makedirs(OUTPUT_FIGURES_DIR, exist_ok=True)
os.makedirs(OUTPUT_MODELS_DIR,  exist_ok=True)
os.makedirs(OUTPUT_RESULTS_DIR, exist_ok=True)
os.makedirs(SCALERS_DIR,        exist_ok=True)

# Reproducibility
np.random.seed(42)
tf.random.set_seed(42)

# Model types we’ll train
MODEL_TYPES = ['Transformer', 'LSTM', 'RNN']

print(f"Input CSV : {INPUT_CSV_PATH}")
print(f"Figures   : {OUTPUT_FIGURES_DIR}")
print(f"Models   : {OUTPUT_MODELS_DIR}")
print(f"Results   : {OUTPUT_RESULTS_DIR}")
print(f"Scalers   : {SCALERS_DIR}")

Input CSV : /content/drive/MyDrive/AML /All/stockprice.csv
Figures   : /content/drive/MyDrive/AML /All/figures_with_cluster
Models   : /content/drive/MyDrive/AML /All/models_1
Results   : /content/drive/MyDrive/AML /All/results_
Scalers   : /content/drive/MyDrive/AML /All/models_1/scalers_1

In [ ]:
# Block 2: Load and Inspect Data

df = pd.read_csv(INPUT_CSV_PATH)
df.columns = df.columns.str.strip()

# Handle common date name variants
if 'trading date' not in df.columns:
    for alt in ['trading_date', 'date', 'Trading Date', 'Trading date']:
        if alt in df.columns:
            df['trading date'] = df[alt]
            break

# Parse date + sort
df['trading date'] = pd.to_datetime(df['trading date'], errors='coerce')
df = df.dropna(subset=['trading date']).sort_values(['sector', 'trading date']).reset_index(drop=True)

print("\n--- Dataset Info ---")
print(df.info())
print("\n--- Head ---")
print(df.head())

sectors = df['sector'].dropna().unique().tolist()
print("\nSectors:", sectors)

--- Dataset Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4270 entries, 0 to 4269
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sector        4270 non-null   object
 1   trading_date  4270 non-null   object
 2   open          4270 non-null   float64
 3   high          4270 non-null   float64
 4   low           4270 non-null   float64
 5   close         4270 non-null   float64
 6   volume        4269 non-null   float64
 7   year          4270 non-null   int64
 8   month         4270 non-null   int64
 9   date          4270 non-null   int64
 10  trading date  4270 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(5), int64(3), object(2)
memory usage: 367.1+ KB
None

--- Head ---
        sector trading_date    open    high     low   close     volume  year  \
0  Engineering   2017-05-02  101.57  102.57   99.90  101.13  399156.61  2017
1  Engineering   2017-05-03  101.41  103.05  100.22  101.16  328356.39  2017
2  Engineering   2017-05-04  101.42  102.16  100.41  100.98  383385.97  2017
3  Engineering   2017-05-07  101.19  102.26  100.33  101.24  346277.30  2017
4  Engineering   2017-05-08  101.46  102.40  100.49  101.36  426731.03  2017

   month  date trading date
0      5     2   2017-05-02
1      5     3   2017-05-03
2      5     4   2017-05-04
3      5     7   2017-05-07
4      5     8   2017-05-08

Sectors: ['Engineering', 'Fuel & Power', 'IT Sector', 'Services & Real Estate', 'Telecommunication']

In [ ]:
# Block 3: Define Time2Vec Layer (for Transformer)

@saving.register_keras_serializable() # Use the imported saving module
class Time2Vec(layers.Layer):
    """
    Minimal Time2Vec: concatenates sin(wa*x+ba) with linear (wb*x+bb) along features.
    Input:  (batch, seq, n_feats)
    Output: (batch, seq, 2*n_feats)
    """
    def __init__(self, kernel_size=1, **kwargs):
        super().__init__(**kwargs)
        self.kernel_size = kernel_size

    def build(self, input_shape):
        self.n_feats = int(input_shape[-1])
        self.wa = self.add_weight(shape=(self.n_feats,), initializer="uniform", trainable=True, name="wa")
        self.ba = self.add_weight(shape=(self.n_feats,), initializer="uniform", trainable=True, name="ba")
        self.wb = self.add_weight(shape=(self.n_feats,), initializer="uniform", trainable=True, name="wb")
        self.bb = self.add_weight(shape=(self.n_feats,), initializer="uniform", trainable=True, name="bb")
        super().build(input_shape)

    def call(self, x):
        v1 = tf.math.sin(x * self.wa + self.ba)
        v2 = x * self.wb + self.bb
        return tf.concat([v1, v2], axis=-1)

In [ ]:
# Block 4: Preprocessing Functions

SEQ_LEN  = 8
FEATURES = ['open', 'high', 'low', 'close', 'volume']
RET_COLS = [f'return_{c}' for c in FEATURES]

def make_stationary_and_scale(group):
    """
    10-day MA smoothing -> differencing (returns) -> dropna -> MinMax scale on returns.
    Returns processed df and fitted scaler.
    """
    g = group.copy()
    smooth = g[FEATURES].rolling(window=10, min_periods=1).mean()
    for c in FEATURES:
        g[f'return_{c}'] = smooth[c].diff()
    g = g.dropna().reset_index(drop=True)

    scaler = MinMaxScaler()
    g[RET_COLS] = scaler.fit_transform(g[RET_COLS])
    return g, scaler

def create_sequences(data, seq_len=SEQ_LEN):
    """
    Build (X, y, last_close):
      X uses previous seq_len returns; y is next-step return_close (scalar).
    """
    X, y, last_closes = [], [], []
    for i in range(seq_len, len(data)):
        X.append(data[RET_COLS].iloc[i-seq_len:i].values)  # (seq_len, 5)
        y.append(data['return_close'].iloc[i])              # scalar
        last_closes.append(data['close'].iloc[i-1])         # for reconstructing price
    return np.array(X), np.array(y), np.array(last_closes)

# Process all sectors → dicts and save scalers
scalers = {}
processed_data_dict = {}

for s in sectors:
    sub = df[df['sector'] == s].copy()
    if len(sub) < SEQ_LEN + 5:
        print(f"Skipping sector {s}: too few rows.")
        continue
    processed, scaler = make_stationary_and_scale(sub)
    X, y, last_closes = create_sequences(processed, SEQ_LEN)

    processed_data_dict[s] = {
        'X': X, 'y': y, 'last_closes': last_closes, 'raw_data': processed
    }
    scalers[s] = scaler
    # save scaler for real-world inference
    joblib.dump(scaler, os.path.join(SCALERS_DIR, f"scaler_{s.replace(' ', '_')}.pkl"))

    print(f"{s}: X{X.shape}, y{y.shape}, last_closes{last_closes.shape}")

print("Preprocessing complete.")

Engineering: X(845, 8, 5), y(845,), last_closes(845,)
Fuel & Power: X(845, 8, 5), y(845,), last_closes(845,)
IT Sector: X(844, 8, 5), y(844,), last_closes(844,)
Services & Real Estate: X(845, 8, 5), y(845,), last_closes(845,)
Telecommunication: X(845, 8, 5), y(845,), last_closes(845,)
Preprocessing complete.

In [ ]:
# Block 5: Define Model Architectures (many-to-one)

def build_transformer_model(
    seq_length=SEQ_LEN,
    n_features=len(FEATURES),
    d_model=32, n_heads=2, d_ff=64, dropout=0.1, lr=1e-3
):
    inputs = layers.Input(shape=(seq_length, n_features), name='sequence_input')

    # Time2Vec
    t2v = Time2Vec(kernel_size=1)(inputs)                 # (batch, seq, 2*n_feats)
    feat_proj = layers.Dense(d_model, name='feature_projection')(inputs)
    time_proj = layers.Dense(d_model, name='time_projection')(t2v)
    x = layers.Add(name='feature_time_fusion')([feat_proj, time_proj])  # (batch, seq, d_model)

    # Positional embedding
    positions = tf.range(start=0, limit=seq_length, delta=1)            # (seq,)
    pos_emb = layers.Embedding(input_dim=seq_length, output_dim=d_model, name='pos_encoding')(positions)
    pos_emb = tf.expand_dims(pos_emb, axis=0)                           # (1, seq, d_model)
    x = layers.Add(name='add_pos_encoding')([x, pos_emb])

    # Encoder block
    x_norm = layers.LayerNormalization(epsilon=1e-6, name='ln_pre_attn')(x)
    attn = layers.MultiHeadAttention(num_heads=n_heads, key_dim=d_model, name='mha')(x_norm, x_norm)
    x = layers.Add(name='resid_attn')([x, layers.Dropout(dropout)(attn)])

    x_norm = layers.LayerNormalization(epsilon=1e-6, name='ln_pre_ffn')(x)
    ffn = layers.Dense(d_ff, activation='gelu', name='ffn1')(x_norm)
    ffn = layers.Dense(d_model, name='ffn2')(ffn)
    x = layers.Add(name='resid_ffn')([x, layers.Dropout(dropout)(ffn)])

    # Many-to-one head
    x_last = layers.Lambda(lambda t: t[:, -1, :], name='take_last')(x)
    x_last = layers.Dense(32, activation='relu')(x_last)
    x_last = layers.Dropout(0.1)(x_last)
    outputs = layers.Dense(1, name='out')(x_last)                       # (batch, 1)

    model = models.Model(inputs, outputs, name="Transformer_Stock")
    model.compile(optimizer=tf.keras.optimizers.Adam(lr), loss='mse', metrics=['mae'])
    return model

def build_lstm_model(seq_length=SEQ_LEN, n_features=len(FEATURES), lstm_units=64, dropout=0.1, lr=1e-3):
    model = models.Sequential(name="LSTM_Stock")
    model.add(layers.Input(shape=(seq_length, n_features)))
    model.add(layers.LSTM(lstm_units, return_sequences=False))
    model.add(layers.Dense(32, activation='relu'))
    model.add(layers.Dropout(dropout))
    model.add(layers.Dense(1))
    model.compile(optimizer=tf.keras.optimizers.Adam(lr), loss='mse', metrics=['mae'])
    return model

def build_rnn_model(seq_length=SEQ_LEN, n_features=len(FEATURES), rnn_units=64, dropout=0.1, lr=1e-3):
    model = models.Sequential(name="RNN_Stock")
    model.add(layers.Input(shape=(seq_length, n_features)))
    model.add(layers.SimpleRNN(rnn_units, return_sequences=False))
    model.add(layers.Dense(32, activation='relu'))
    model.add(layers.Dropout(dropout))
    model.add(layers.Dense(1))
    model.compile(optimizer=tf.keras.optimizers.Adam(lr), loss='mse', metrics=['mae'])
    return model

In [ ]:
# Block 6: Train Models (per-sector), Evaluate & Store

def ensure_targets_column(y):
    y = np.asarray(y)
    return y.reshape(-1, 1) if y.ndim == 1 else y

def ts_split(X, y, train_ratio=0.8, val_ratio=0.1):
    n = X.shape[0]
    n_train = max(1, int(n*train_ratio))
    n_val   = max(1, int(n*val_ratio))
    n_test  = max(1, n - n_train - n_val)
    if n_train + n_val + n_test > n:
        n_test = max(1, n - n_train - n_val)
    Xtr, ytr = X[:n_train], y[:n_train]
    Xv,  yv  = X[n_train:n_train+n_val], y[n_train:n_train+n_val]
    Xte, yte = X[n_train+n_val:], y[n_train+n_val:]
    return Xtr, ytr, Xv, yv, Xte, yte

def build_model_by_name(name, seq_len, n_feats):
    if name == 'Transformer': return build_transformer_model(seq_len, n_feats)
    if name == 'LSTM':       return build_lstm_model(seq_len, n_feats)
    if name == 'RNN':        return build_rnn_model(seq_len, n_feats)
    raise ValueError(name)

EPOCHS = 50
BATCH_SIZE = 32
EARLY_STOP = callbacks.EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

all_results = {m: {} for m in MODEL_TYPES}
model_histories = {m: {} for m in MODEL_TYPES}

for sector in sectors:
    if sector not in processed_data_dict:
        continue
    print(f"\n===== Sector: {sector} =====")
    pack = processed_data_dict[sector]
    X, y = pack['X'], ensure_targets_column(pack['y'])
    last_closes = pack['last_closes']
    seq_len, n_feats = X.shape[1], X.shape[2]

    Xtr, ytr, Xv, yv, Xte, yte = ts_split(X, y, 0.8, 0.1)
    last_closes_test = last_closes[len(ytr)+len(yv):]

    for model_type in MODEL_TYPES:
        print(f"\n--- {model_type} ---")
        model = build_model_by_name(model_type, seq_len, n_feats)

        hist = model.fit(
            Xtr, ytr,
            validation_data=(Xv, yv),
            epochs=EPOCHS, batch_size=BATCH_SIZE, verbose=1,
            callbacks=[EARLY_STOP]
        )
        model_histories[model_type][sector] = hist

        # Evaluate on TEST (normalized)
        test_mse, test_mae = model.evaluate(Xte, yte, verbose=0)

        # Inverse-transform returns to real closing prices (close-only trick)
        feature_cols = RET_COLS
        close_idx = feature_cols.index('return_close')
        scaler = scalers[sector]

        def invert_close_only(arr_norm_1d):
            dummy = np.zeros((len(arr_norm_1d), len(feature_cols)))
            dummy[:, close_idx] = arr_norm_1d
            inv = scaler.inverse_transform(dummy)
            return inv[:, close_idx]

        y_pred_norm = model.predict(Xte, verbose=0).reshape(-1)
        y_test_norm = yte.reshape(-1)
        y_pred_actual_returns = invert_close_only(y_pred_norm)
        y_test_actual_returns = invert_close_only(y_test_norm)

        # Reconstruct prices: close_t ≈ close_{t-1} + diff
        predicted_prices = last_closes_test + y_pred_actual_returns
        actual_prices    = last_closes_test + y_test_actual_returns

        # Price-space metrics
        rmse_actual = np.sqrt(mean_squared_error(actual_prices, predicted_prices))
        mae_actual  = mean_absolute_error(actual_prices, predicted_prices)

        all_results[model_type][sector] = {
            'RMSE_Actual_Return': float(rmse_actual),
            'MAE_Actual_Return':  float(mae_actual),
            'actual_closing_prices': actual_prices,
            'predicted_closing_prices': predicted_prices,
        }

        # Save model
        model_path = os.path.join(OUTPUT_MODELS_DIR, f"{model_type}_model_{sector.replace(' ', '_')}.keras")
        model.save(model_path)
        print(f"{model_type} saved → {model_path} | Test MSE={test_mse:.6f} MAE={test_mae:.6f} | "
              f"Price RMSE={rmse_actual:.6f} MAE={mae_actual:.6f}")

print("\nPer-sector training complete.")

===== Sector: Engineering =====

--- Transformer ---
Epoch 1/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 6s 26ms/step - loss: 0.0799 - mae: 0.2223 - val_loss: 0.0172 - val_mae: 0.1190
Epoch 2/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0280 - mae: 0.1288 - val_loss: 0.0156 - val_mae: 0.1167
Epoch 3/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0219 - mae: 0.1145 - val_loss: 0.0083 - val_mae: 0.0806
Epoch 4/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0166 - mae: 0.0983 - val_loss: 0.0026 - val_mae: 0.0391
Epoch 5/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0130 - mae: 0.0832 - val_loss: 0.0022 - val_mae: 0.0340
Epoch 6/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0131 - mae: 0.0830 - val_loss: 0.0019 - val_mae: 0.0304
Epoch 7/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0131 - mae: 0.0847 - val_loss: 0.0046 - val_mae: 0.0594
Epoch 8/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0134 - mae: 0.0812 - val_loss: 0.0029 - val_mae: 0.0427
Epoch 9/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0122 - mae: 0.0799 - val_loss: 0.0026 - val_mae: 0.0388
Epoch 10/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0103 - mae: 0.0730 - val_loss: 0.0054 - val_mae: 0.0644
Epoch 11/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0130 - mae: 0.0797 - val_loss: 0.0052 - val_mae: 0.0631
Transformer saved → /content/drive/MyDrive/AML /All/models_1/Transformer_model_Engineering.keras | Test MSE=0.001251 MAE=0.026261 | Price RMSE=0.921756 MAE=0.684283

--- LSTM ---
Epoch 1/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.1312 - mae: 0.3168 - val_loss: 0.0030 - val_mae: 0.0397
Epoch 2/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0170 - mae: 0.0884 - val_loss: 0.0027 - val_mae: 0.0385
Epoch 3/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0145 - mae: 0.0833 - val_loss: 0.0030 - val_mae: 0.0395
Epoch 4/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0142 - mae: 0.0831 - val_loss: 0.0029 - val_mae: 0.0386
Epoch 5/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0118 - mae: 0.0784 - val_loss: 0.0029 - val_mae: 0.0378
Epoch 6/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0115 - mae: 0.0748 - val_loss: 0.0026 - val_mae: 0.0369
Epoch 7/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0110 - mae: 0.0765 - val_loss: 0.0026 - val_mae: 0.0374
Epoch 8/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0107 - mae: 0.0719 - val_loss: 0.0024 - val_mae: 0.0352
Epoch 9/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0104 - mae: 0.0689 - val_loss: 0.0028 - val_mae: 0.0372
Epoch 10/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0105 - mae: 0.0712 - val_loss: 0.0024 - val_mae: 0.0352
Epoch 11/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0093 - mae: 0.0663 - val_loss: 0.0030 - val_mae: 0.0395
Epoch 12/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0091 - mae: 0.0649 - val_loss: 0.0023 - val_mae: 0.0329
Epoch 13/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0091 - mae: 0.0648 - val_loss: 0.0029 - val_mae: 0.0382
Epoch 14/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0084 - mae: 0.0636 - val_loss: 0.0026 - val_mae: 0.0351
Epoch 15/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0089 - mae: 0.0621 - val_loss: 0.0022 - val_mae: 0.0321
Epoch 16/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0076 - mae: 0.0608 - val_loss: 0.0022 - val_mae: 0.0314
Epoch 17/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0080 - mae: 0.0600 - val_loss: 0.0024 - val_mae: 0.0325
Epoch 18/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0079 - mae: 0.0579 - val_loss: 0.0025 - val_mae: 0.0340
Epoch 19/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0081 - mae: 0.0611 - val_loss: 0.0022 - val_mae: 0.0314
Epoch 20/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0074 - mae: 0.0603 - val_loss: 0.0021 - val_mae: 0.0309
Epoch 21/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0077 - mae: 0.0579 - val_loss: 0.0021 - val_mae: 0.0308
Epoch 22/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0073 - mae: 0.0577 - val_loss: 0.0024 - val_mae: 0.0332
Epoch 23/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0077 - mae: 0.0583 - val_loss: 0.0030 - val_mae: 0.0405
Epoch 24/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0078 - mae: 0.0615 - val_loss: 0.0028 - val_mae: 0.0384
Epoch 25/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0078 - mae: 0.0593 - val_loss: 0.0021 - val_mae: 0.0307
Epoch 26/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0077 - mae: 0.0602 - val_loss: 0.0024 - val_mae: 0.0338
Epoch 27/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0079 - mae: 0.0595 - val_loss: 0.0026 - val_mae: 0.0359
Epoch 28/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0071 - mae: 0.0578 - val_loss: 0.0022 - val_mae: 0.0311
Epoch 29/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0082 - mae: 0.0594 - val_loss: 0.0026 - val_mae: 0.0366
Epoch 30/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0079 - mae: 0.0597 - val_loss: 0.0023 - val_mae: 0.0328
LSTM saved → /content/drive/MyDrive/AML /All/models_1/LSTM_model_Engineering.keras | Test MSE=0.000898 MAE=0.019788 | Price RMSE=0.780778 MAE=0.515608

--- RNN ---
Epoch 1/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - loss: 0.0486 - mae: 0.1737 - val_loss: 0.0100 - val_mae: 0.0860
Epoch 2/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0158 - mae: 0.0929 - val_loss: 0.0044 - val_mae: 0.0506
Epoch 3/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0118 - mae: 0.0822 - val_loss: 0.0045 - val_mae: 0.0514
Epoch 4/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0098 - mae: 0.0727 - val_loss: 0.0051 - val_mae: 0.0544
Epoch 5/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0108 - mae: 0.0727 - val_loss: 0.0036 - val_mae: 0.0471
Epoch 6/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0097 - mae: 0.0685 - val_loss: 0.0034 - val_mae: 0.0450
Epoch 7/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0096 - mae: 0.0716 - val_loss: 0.0033 - val_mae: 0.0437
Epoch 8/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0093 - mae: 0.0690 - val_loss: 0.0081 - val_mae: 0.0745
Epoch 9/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0105 - mae: 0.0736 - val_loss: 0.0027 - val_mae: 0.0390
Epoch 10/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0096 - mae: 0.0711 - val_loss: 0.0028 - val_mae: 0.0407
Epoch 11/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0099 - mae: 0.0694 - val_loss: 0.0052 - val_mae: 0.0572
Epoch 12/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0089 - mae: 0.0647 - val_loss: 0.0032 - val_mae: 0.0456
Epoch 13/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0084 - mae: 0.0634 - val_loss: 0.0047 - val_mae: 0.0539
Epoch 14/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0076 - mae: 0.0611 - val_loss: 0.0030 - val_mae: 0.0404

WARNING:tensorflow:5 out of the last 7 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x7bd61b2f5e40> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:6 out of the last 9 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x7bd61b2f5e40> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

RNN saved → /content/drive/MyDrive/AML /All/models_1/RNN_model_Engineering.keras | Test MSE=0.001046 MAE=0.022153 | Price RMSE=0.842759 MAE=0.577248

===== Sector: Fuel & Power =====

--- Transformer ---
Epoch 1/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 6s 28ms/step - loss: 0.2363 - mae: 0.3720 - val_loss: 0.0120 - val_mae: 0.0897
Epoch 2/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0431 - mae: 0.1613 - val_loss: 0.0089 - val_mae: 0.0712
Epoch 3/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0246 - mae: 0.1213 - val_loss: 0.0059 - val_mae: 0.0444
Epoch 4/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0179 - mae: 0.1027 - val_loss: 0.0094 - val_mae: 0.0723
Epoch 5/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0195 - mae: 0.1049 - val_loss: 0.0081 - val_mae: 0.0626
Epoch 6/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0156 - mae: 0.0910 - val_loss: 0.0063 - val_mae: 0.0460
Epoch 7/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0137 - mae: 0.0904 - val_loss: 0.0067 - val_mae: 0.0500
Epoch 8/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0137 - mae: 0.0858 - val_loss: 0.0098 - val_mae: 0.0768
Transformer saved → /content/drive/MyDrive/AML /All/models_1/Transformer_model_Fuel_&_Power.keras | Test MSE=0.013856 MAE=0.092278 | Price RMSE=1.668649 MAE=1.308134

--- LSTM ---
Epoch 1/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 3s 21ms/step - loss: 0.2492 - mae: 0.4475 - val_loss: 0.0194 - val_mae: 0.1231
Epoch 2/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0182 - mae: 0.1056 - val_loss: 0.0069 - val_mae: 0.0569
Epoch 3/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0119 - mae: 0.0828 - val_loss: 0.0068 - val_mae: 0.0557
Epoch 4/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0100 - mae: 0.0715 - val_loss: 0.0063 - val_mae: 0.0517
Epoch 5/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0101 - mae: 0.0722 - val_loss: 0.0059 - val_mae: 0.0475
Epoch 6/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0103 - mae: 0.0717 - val_loss: 0.0067 - val_mae: 0.0553
Epoch 7/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0120 - mae: 0.0729 - val_loss: 0.0069 - val_mae: 0.0567
Epoch 8/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0104 - mae: 0.0717 - val_loss: 0.0060 - val_mae: 0.0482
Epoch 9/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0102 - mae: 0.0718 - val_loss: 0.0059 - val_mae: 0.0468
Epoch 10/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0098 - mae: 0.0715 - val_loss: 0.0062 - val_mae: 0.0501
Epoch 11/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0086 - mae: 0.0644 - val_loss: 0.0060 - val_mae: 0.0483
Epoch 12/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0103 - mae: 0.0709 - val_loss: 0.0060 - val_mae: 0.0476
Epoch 13/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0091 - mae: 0.0687 - val_loss: 0.0057 - val_mae: 0.0450
Epoch 14/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0103 - mae: 0.0735 - val_loss: 0.0054 - val_mae: 0.0424
Epoch 15/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0106 - mae: 0.0745 - val_loss: 0.0055 - val_mae: 0.0431
Epoch 16/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0092 - mae: 0.0693 - val_loss: 0.0056 - val_mae: 0.0440
Epoch 17/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0086 - mae: 0.0652 - val_loss: 0.0057 - val_mae: 0.0445
Epoch 18/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0089 - mae: 0.0667 - val_loss: 0.0060 - val_mae: 0.0481
Epoch 19/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0098 - mae: 0.0699 - val_loss: 0.0064 - val_mae: 0.0515
LSTM saved → /content/drive/MyDrive/AML /All/models_1/LSTM_model_Fuel_&_Power.keras | Test MSE=0.013694 MAE=0.092557 | Price RMSE=1.658904 MAE=1.312094

--- RNN ---
Epoch 1/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - loss: 0.1005 - mae: 0.2387 - val_loss: 0.0078 - val_mae: 0.0589
Epoch 2/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0154 - mae: 0.0898 - val_loss: 0.0072 - val_mae: 0.0544
Epoch 3/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0116 - mae: 0.0780 - val_loss: 0.0075 - val_mae: 0.0566
Epoch 4/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0107 - mae: 0.0759 - val_loss: 0.0060 - val_mae: 0.0445
Epoch 5/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0103 - mae: 0.0758 - val_loss: 0.0059 - val_mae: 0.0437
Epoch 6/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0105 - mae: 0.0769 - val_loss: 0.0057 - val_mae: 0.0427
Epoch 7/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0111 - mae: 0.0763 - val_loss: 0.0058 - val_mae: 0.0441
Epoch 8/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0113 - mae: 0.0747 - val_loss: 0.0069 - val_mae: 0.0528
Epoch 9/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0096 - mae: 0.0708 - val_loss: 0.0056 - val_mae: 0.0417
Epoch 10/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0104 - mae: 0.0734 - val_loss: 0.0057 - val_mae: 0.0432
Epoch 11/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0095 - mae: 0.0687 - val_loss: 0.0055 - val_mae: 0.0421
Epoch 12/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0099 - mae: 0.0713 - val_loss: 0.0059 - val_mae: 0.0448
Epoch 13/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0104 - mae: 0.0733 - val_loss: 0.0054 - val_mae: 0.0414
Epoch 14/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0094 - mae: 0.0690 - val_loss: 0.0055 - val_mae: 0.0426
Epoch 15/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0101 - mae: 0.0711 - val_loss: 0.0059 - val_mae: 0.0464
Epoch 16/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0081 - mae: 0.0638 - val_loss: 0.0058 - val_mae: 0.0453
Epoch 17/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0088 - mae: 0.0667 - val_loss: 0.0057 - val_mae: 0.0444
Epoch 18/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0091 - mae: 0.0675 - val_loss: 0.0058 - val_mae: 0.0452
RNN saved → /content/drive/MyDrive/AML /All/models_1/RNN_model_Fuel_&_Power.keras | Test MSE=0.010670 MAE=0.083629 | Price RMSE=1.464325 MAE=1.185529

===== Sector: IT Sector =====

--- Transformer ---
Epoch 1/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 6s 44ms/step - loss: 0.0839 - mae: 0.2196 - val_loss: 0.0165 - val_mae: 0.1146
Epoch 2/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0195 - mae: 0.1079 - val_loss: 0.0043 - val_mae: 0.0474
Epoch 3/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0155 - mae: 0.0943 - val_loss: 0.0071 - val_mae: 0.0690
Epoch 4/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0149 - mae: 0.0893 - val_loss: 0.0043 - val_mae: 0.0491
Epoch 5/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0148 - mae: 0.0903 - val_loss: 0.0043 - val_mae: 0.0469
Epoch 6/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0131 - mae: 0.0841 - val_loss: 0.0041 - val_mae: 0.0478
Epoch 7/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0117 - mae: 0.0813 - val_loss: 0.0057 - val_mae: 0.0598
Epoch 8/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0106 - mae: 0.0793 - val_loss: 0.0045 - val_mae: 0.0502
Epoch 9/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0101 - mae: 0.0755 - val_loss: 0.0042 - val_mae: 0.0465
Epoch 10/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0118 - mae: 0.0809 - val_loss: 0.0072 - val_mae: 0.0694
Epoch 11/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0103 - mae: 0.0717 - val_loss: 0.0043 - val_mae: 0.0464
Transformer saved → /content/drive/MyDrive/AML /All/models_1/Transformer_model_IT_Sector.keras | Test MSE=0.014569 MAE=0.073803 | Price RMSE=0.303443 MAE=0.185541

--- LSTM ---
Epoch 1/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0488 - mae: 0.1805 - val_loss: 0.0116 - val_mae: 0.0915
Epoch 2/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0114 - mae: 0.0762 - val_loss: 0.0054 - val_mae: 0.0588
Epoch 3/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0099 - mae: 0.0735 - val_loss: 0.0053 - val_mae: 0.0575
Epoch 4/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0098 - mae: 0.0690 - val_loss: 0.0049 - val_mae: 0.0549
Epoch 5/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0094 - mae: 0.0720 - val_loss: 0.0046 - val_mae: 0.0529
Epoch 6/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0103 - mae: 0.0718 - val_loss: 0.0044 - val_mae: 0.0514
Epoch 7/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0096 - mae: 0.0712 - val_loss: 0.0045 - val_mae: 0.0512
Epoch 8/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0090 - mae: 0.0681 - val_loss: 0.0050 - val_mae: 0.0550
Epoch 9/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0085 - mae: 0.0652 - val_loss: 0.0045 - val_mae: 0.0509
Epoch 10/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0089 - mae: 0.0652 - val_loss: 0.0055 - val_mae: 0.0591
Epoch 11/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0077 - mae: 0.0628 - val_loss: 0.0046 - val_mae: 0.0518
LSTM saved → /content/drive/MyDrive/AML /All/models_1/LSTM_model_IT_Sector.keras | Test MSE=0.012095 MAE=0.076362 | Price RMSE=0.276484 MAE=0.191973

--- RNN ---
Epoch 1/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - loss: 0.0980 - mae: 0.2455 - val_loss: 0.0088 - val_mae: 0.0760
Epoch 2/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0153 - mae: 0.0920 - val_loss: 0.0114 - val_mae: 0.0910
Epoch 3/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0119 - mae: 0.0782 - val_loss: 0.0054 - val_mae: 0.0580
Epoch 4/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0120 - mae: 0.0834 - val_loss: 0.0054 - val_mae: 0.0576
Epoch 5/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0102 - mae: 0.0725 - val_loss: 0.0062 - val_mae: 0.0644
Epoch 6/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0108 - mae: 0.0720 - val_loss: 0.0048 - val_mae: 0.0542
Epoch 7/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0097 - mae: 0.0702 - val_loss: 0.0050 - val_mae: 0.0539
Epoch 8/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0092 - mae: 0.0677 - val_loss: 0.0049 - val_mae: 0.0530
Epoch 9/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0094 - mae: 0.0718 - val_loss: 0.0043 - val_mae: 0.0506
Epoch 10/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0119 - mae: 0.0822 - val_loss: 0.0101 - val_mae: 0.0859
Epoch 11/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0114 - mae: 0.0757 - val_loss: 0.0051 - val_mae: 0.0569
Epoch 12/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0090 - mae: 0.0691 - val_loss: 0.0064 - val_mae: 0.0642
Epoch 13/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0093 - mae: 0.0709 - val_loss: 0.0051 - val_mae: 0.0561
Epoch 14/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0092 - mae: 0.0693 - val_loss: 0.0044 - val_mae: 0.0506
RNN saved → /content/drive/MyDrive/AML /All/models_1/RNN_model_IT_Sector.keras | Test MSE=0.012230 MAE=0.072248 | Price RMSE=0.278020 MAE=0.181631

===== Sector: Services & Real Estate =====

--- Transformer ---
Epoch 1/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 5s 25ms/step - loss: 0.3915 - mae: 0.4742 - val_loss: 0.0065 - val_mae: 0.0657
Epoch 2/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0379 - mae: 0.1497 - val_loss: 0.0054 - val_mae: 0.0728
Epoch 3/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0186 - mae: 0.1030 - val_loss: 0.0031 - val_mae: 0.0521
Epoch 4/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0134 - mae: 0.0904 - val_loss: 0.0048 - val_mae: 0.0670
Epoch 5/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0148 - mae: 0.0920 - val_loss: 0.0069 - val_mae: 0.0810
Epoch 6/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0114 - mae: 0.0802 - val_loss: 0.0044 - val_mae: 0.0633
Epoch 7/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0104 - mae: 0.0773 - val_loss: 0.0019 - val_mae: 0.0397
Epoch 8/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0110 - mae: 0.0804 - val_loss: 0.0014 - val_mae: 0.0340
Epoch 9/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0088 - mae: 0.0704 - val_loss: 0.0024 - val_mae: 0.0470
Epoch 10/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0085 - mae: 0.0710 - val_loss: 0.0028 - val_mae: 0.0518
Epoch 11/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0093 - mae: 0.0744 - val_loss: 0.0051 - val_mae: 0.0710
Epoch 12/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0082 - mae: 0.0690 - val_loss: 0.0037 - val_mae: 0.0602
Epoch 13/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0077 - mae: 0.0641 - val_loss: 0.0036 - val_mae: 0.0581
Transformer saved → /content/drive/MyDrive/AML /All/models_1/Transformer_model_Services_&_Real_Estate.keras | Test MSE=0.001119 MAE=0.028024 | Price RMSE=1.080543 MAE=0.905249

--- LSTM ---
Epoch 1/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 3s 21ms/step - loss: 0.2017 - mae: 0.3991 - val_loss: 0.0014 - val_mae: 0.0308
Epoch 2/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0123 - mae: 0.0783 - val_loss: 2.9709e-04 - val_mae: 0.0142
Epoch 3/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0099 - mae: 0.0683 - val_loss: 4.8770e-04 - val_mae: 0.0174
Epoch 4/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0082 - mae: 0.0646 - val_loss: 5.6522e-04 - val_mae: 0.0208
Epoch 5/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0062 - mae: 0.0590 - val_loss: 5.1838e-04 - val_mae: 0.0194
Epoch 6/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0051 - mae: 0.0542 - val_loss: 5.4404e-04 - val_mae: 0.0207
Epoch 7/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0052 - mae: 0.0557 - val_loss: 5.3612e-04 - val_mae: 0.0206
LSTM saved → /content/drive/MyDrive/AML /All/models_1/LSTM_model_Services_&_Real_Estate.keras | Test MSE=0.000187 MAE=0.009499 | Price RMSE=0.441165 MAE=0.306835

--- RNN ---
Epoch 1/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - loss: 0.1892 - mae: 0.3305 - val_loss: 0.0094 - val_mae: 0.0874
Epoch 2/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0210 - mae: 0.1066 - val_loss: 7.5832e-04 - val_mae: 0.0211
Epoch 3/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0073 - mae: 0.0643 - val_loss: 0.0015 - val_mae: 0.0370
Epoch 4/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0052 - mae: 0.0510 - val_loss: 0.0019 - val_mae: 0.0416
Epoch 5/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0053 - mae: 0.0512 - val_loss: 0.0013 - val_mae: 0.0308
Epoch 6/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0040 - mae: 0.0438 - val_loss: 0.0012 - val_mae: 0.0295
Epoch 7/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0039 - mae: 0.0409 - val_loss: 5.1860e-04 - val_mae: 0.0187
Epoch 8/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0037 - mae: 0.0433 - val_loss: 7.7774e-04 - val_mae: 0.0227
Epoch 9/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0034 - mae: 0.0409 - val_loss: 2.7753e-04 - val_mae: 0.0130
Epoch 10/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0041 - mae: 0.0456 - val_loss: 0.0010 - val_mae: 0.0269
Epoch 11/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0043 - mae: 0.0451 - val_loss: 0.0025 - val_mae: 0.0467
Epoch 12/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0048 - mae: 0.0508 - val_loss: 2.8452e-04 - val_mae: 0.0120
Epoch 13/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0036 - mae: 0.0417 - val_loss: 6.8610e-04 - val_mae: 0.0205
Epoch 14/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0030 - mae: 0.0399 - val_loss: 0.0010 - val_mae: 0.0277
RNN saved → /content/drive/MyDrive/AML /All/models_1/RNN_model_Services_&_Real_Estate.keras | Test MSE=0.000348 MAE=0.013433 | Price RMSE=0.602634 MAE=0.433935

===== Sector: Telecommunication =====

--- Transformer ---
Epoch 1/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 6s 25ms/step - loss: 0.1797 - mae: 0.3179 - val_loss: 0.0189 - val_mae: 0.1335
Epoch 2/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0394 - mae: 0.1519 - val_loss: 0.0086 - val_mae: 0.0865
Epoch 3/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0204 - mae: 0.1077 - val_loss: 0.0032 - val_mae: 0.0425
Epoch 4/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0175 - mae: 0.1006 - val_loss: 0.0092 - val_mae: 0.0893
Epoch 5/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0161 - mae: 0.0954 - val_loss: 0.0037 - val_mae: 0.0493
Epoch 6/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0152 - mae: 0.0943 - val_loss: 0.0045 - val_mae: 0.0559
Epoch 7/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0134 - mae: 0.0859 - val_loss: 0.0041 - val_mae: 0.0515
Epoch 8/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0143 - mae: 0.0871 - val_loss: 0.0098 - val_mae: 0.0931
Transformer saved → /content/drive/MyDrive/AML /All/models_1/Transformer_model_Telecommunication.keras | Test MSE=0.001660 MAE=0.030515 | Price RMSE=1.638900 MAE=1.227332

--- LSTM ---
Epoch 1/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0633 - mae: 0.2044 - val_loss: 0.0065 - val_mae: 0.0739
Epoch 2/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0094 - mae: 0.0682 - val_loss: 0.0024 - val_mae: 0.0307
Epoch 3/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0086 - mae: 0.0621 - val_loss: 0.0021 - val_mae: 0.0239
Epoch 4/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0070 - mae: 0.0561 - val_loss: 0.0022 - val_mae: 0.0273
Epoch 5/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0079 - mae: 0.0563 - val_loss: 0.0026 - val_mae: 0.0345
Epoch 6/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0075 - mae: 0.0565 - val_loss: 0.0028 - val_mae: 0.0366
Epoch 7/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0076 - mae: 0.0580 - val_loss: 0.0023 - val_mae: 0.0284
Epoch 8/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0068 - mae: 0.0535 - val_loss: 0.0025 - val_mae: 0.0318
LSTM saved → /content/drive/MyDrive/AML /All/models_1/LSTM_model_Telecommunication.keras | Test MSE=0.000895 MAE=0.015445 | Price RMSE=1.203033 MAE=0.621188

--- RNN ---
Epoch 1/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - loss: 0.0226 - mae: 0.1178 - val_loss: 0.0023 - val_mae: 0.0234
Epoch 2/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0087 - mae: 0.0666 - val_loss: 0.0031 - val_mae: 0.0406
Epoch 3/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0069 - mae: 0.0586 - val_loss: 0.0031 - val_mae: 0.0400
Epoch 4/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0085 - mae: 0.0672 - val_loss: 0.0021 - val_mae: 0.0214
Epoch 5/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0072 - mae: 0.0580 - val_loss: 0.0020 - val_mae: 0.0201
Epoch 6/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0068 - mae: 0.0553 - val_loss: 0.0020 - val_mae: 0.0186
Epoch 7/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0072 - mae: 0.0577 - val_loss: 0.0022 - val_mae: 0.0235
Epoch 8/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0080 - mae: 0.0599 - val_loss: 0.0028 - val_mae: 0.0367
Epoch 9/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0077 - mae: 0.0589 - val_loss: 0.0020 - val_mae: 0.0196
Epoch 10/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0073 - mae: 0.0565 - val_loss: 0.0020 - val_mae: 0.0191
Epoch 11/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0073 - mae: 0.0578 - val_loss: 0.0023 - val_mae: 0.0279
Epoch 12/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0082 - mae: 0.0634 - val_loss: 0.0019 - val_mae: 0.0192
Epoch 13/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0069 - mae: 0.0554 - val_loss: 0.0019 - val_mae: 0.0191
Epoch 14/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0073 - mae: 0.0569 - val_loss: 0.0025 - val_mae: 0.0319
Epoch 15/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0066 - mae: 0.0554 - val_loss: 0.0021 - val_mae: 0.0239
Epoch 16/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0071 - mae: 0.0543 - val_loss: 0.0020 - val_mae: 0.0221
Epoch 17/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0059 - mae: 0.0511 - val_loss: 0.0026 - val_mae: 0.0346
Epoch 18/50
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0069 - mae: 0.0545 - val_loss: 0.0025 - val_mae: 0.0313
RNN saved → /content/drive/MyDrive/AML /All/models_1/RNN_model_Telecommunication.keras | Test MSE=0.000766 MAE=0.015754 | Price RMSE=1.113397 MAE=0.633615

Per-sector training complete.

In [ ]:
# Block 6b: Train OVERALL (pooled) models

def concat_overall(processed_data_dict, sectors):
    Xs, ys = [], []
    for s in sectors:
        if s in processed_data_dict:
            Xs.append(processed_data_dict[s]['X'])
            ys.append(ensure_targets_column(processed_data_dict[s]['y']))
    return np.concatenate(Xs, 0), np.concatenate(ys, 0)

X_all, y_all = concat_overall(processed_data_dict, sectors)
seq_len_all, n_feats_all = X_all.shape[1], X_all.shape[2]
Xtr_all, ytr_all, Xv_all, yv_all, Xte_all, yte_all = ts_split(X_all, y_all, 0.8, 0.1)
print(f"OVERALL: Train {Xtr_all.shape}, Val {Xv_all.shape}, Test {Xte_all.shape}")

model_histories_overall = {}
all_results_overall = {}

for model_type in MODEL_TYPES:
    print(f"\n=== OVERALL {model_type} ===")
    model = build_model_by_name(model_type, seq_len_all, n_feats_all)
    hist = model.fit(
        Xtr_all, ytr_all,
        validation_data=(Xv_all, yv_all),
        epochs=EPOCHS, batch_size=BATCH_SIZE, verbose=1,
        callbacks=[EARLY_STOP]
    )
    model_histories_overall[model_type] = hist

    mse, mae = model.evaluate(Xte_all, yte_all, verbose=0)
    all_results_overall[model_type] = {"Test_MSE": float(mse), "Test_MAE": float(mae)}

    path = os.path.join(OUTPUT_MODELS_DIR, f"{model_type}_model_OVERALL.keras")
    model.save(path)
    print(f"Saved OVERALL → {path} | Test MSE={mse:.6f} MAE={mae:.6f}")

OVERALL: Train (3379, 8, 5), Val (422, 8, 5), Test (423, 8, 5)

=== OVERALL Transformer ===
Epoch 1/50
106/106 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - loss: 0.7895 - mae: 0.4954 - val_loss: 0.0067 - val_mae: 0.0289
Epoch 2/50
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0209 - mae: 0.1110 - val_loss: 0.0069 - val_mae: 0.0323
Epoch 3/50
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0162 - mae: 0.0955 - val_loss: 0.0075 - val_mae: 0.0319
Epoch 4/50
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0139 - mae: 0.0878 - val_loss: 0.0077 - val_mae: 0.0329
Epoch 5/50
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0121 - mae: 0.0814 - val_loss: 0.0084 - val_mae: 0.0406
Epoch 6/50
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0110 - mae: 0.0765 - val_loss: 0.0082 - val_mae: 0.0337
Saved OVERALL → /content/drive/MyDrive/AML /All/models/Transformer_model_OVERALL.keras | Test MSE=0.002355 MAE=0.023170

=== OVERALL LSTM ===
Epoch 1/50
106/106 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 0.0233 - mae: 0.1106 - val_loss: 0.0067 - val_mae: 0.0338
Epoch 2/50
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0087 - mae: 0.0666 - val_loss: 0.0067 - val_mae: 0.0329
Epoch 3/50
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0077 - mae: 0.0617 - val_loss: 0.0068 - val_mae: 0.0339
Epoch 4/50
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0077 - mae: 0.0617 - val_loss: 0.0069 - val_mae: 0.0326
Epoch 5/50
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0071 - mae: 0.0582 - val_loss: 0.0070 - val_mae: 0.0324
Epoch 6/50
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0069 - mae: 0.0585 - val_loss: 0.0074 - val_mae: 0.0397
Saved OVERALL → /content/drive/MyDrive/AML /All/models/LSTM_model_OVERALL.keras | Test MSE=0.002207 MAE=0.024100

=== OVERALL RNN ===
Epoch 1/50
106/106 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 0.0161 - mae: 0.0929 - val_loss: 0.0087 - val_mae: 0.0587
Epoch 2/50
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0076 - mae: 0.0631 - val_loss: 0.0076 - val_mae: 0.0395
Epoch 3/50
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0071 - mae: 0.0592 - val_loss: 0.0075 - val_mae: 0.0345
Epoch 4/50
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0068 - mae: 0.0578 - val_loss: 0.0074 - val_mae: 0.0335
Epoch 5/50
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0066 - mae: 0.0559 - val_loss: 0.0076 - val_mae: 0.0391
Epoch 6/50
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0062 - mae: 0.0536 - val_loss: 0.0075 - val_mae: 0.0367
Epoch 7/50
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0066 - mae: 0.0547 - val_loss: 0.0075 - val_mae: 0.0343
Epoch 8/50
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0064 - mae: 0.0546 - val_loss: 0.0073 - val_mae: 0.0342
Epoch 9/50
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0058 - mae: 0.0521 - val_loss: 0.0074 - val_mae: 0.0336
Epoch 10/50
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0056 - mae: 0.0500 - val_loss: 0.0077 - val_mae: 0.0414
Epoch 11/50
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0057 - mae: 0.0503 - val_loss: 0.0074 - val_mae: 0.0338
Epoch 12/50
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0056 - mae: 0.0475 - val_loss: 0.0074 - val_mae: 0.0351
Epoch 13/50
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0055 - mae: 0.0481 - val_loss: 0.0072 - val_mae: 0.0323
Epoch 14/50
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0054 - mae: 0.0481 - val_loss: 0.0073 - val_mae: 0.0340
Epoch 15/50
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0049 - mae: 0.0454 - val_loss: 0.0071 - val_mae: 0.0316
Epoch 16/50
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0050 - mae: 0.0446 - val_loss: 0.0072 - val_mae: 0.0322
Epoch 17/50
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0050 - mae: 0.0447 - val_loss: 0.0072 - val_mae: 0.0321
Epoch 18/50
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0050 - mae: 0.0441 - val_loss: 0.0073 - val_mae: 0.0346
Epoch 19/50
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0047 - mae: 0.0430 - val_loss: 0.0071 - val_mae: 0.0340
Epoch 20/50
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0049 - mae: 0.0434 - val_loss: 0.0073 - val_mae: 0.0368
Saved OVERALL → /content/drive/MyDrive/AML /All/models/RNN_model_OVERALL.keras | Test MSE=0.002146 MAE=0.022255

In [ ]:
# Block 7: Build comparison tables (Train/Val/Test) as DataFrames & CSVs

# --- Incorporate relevant parts from Block 6b to ensure variables are defined ---
# This is done to make this cell runnable even if Block 6b wasn't executed directly before it.

def ensure_targets_column(y):
    y = np.asarray(y)
    return y.reshape(-1, 1) if y.ndim == 1 else y

def ts_split(X, y, train_ratio=0.8, val_ratio=0.1):
    n = X.shape[0]
    n_train = max(1, int(n*train_ratio))
    n_val   = max(1, int(n*val_ratio))
    n_test  = max(1, n - n_train - n_val)
    if n_train + n_val + n_test > n:
        n_test = max(1, n - n_train - n_val)
    Xtr, ytr = X[:n_train], y[:n_train]
    Xv,  yv  = X[n_train:n_train+n_val], y[n_train:n_train+n_val]
    Xte, yte = X[n_train+n_val:], y[n_train+n_val:]
    return Xtr, ytr, Xv, yv, Xte, yte

def build_model_by_name(name, seq_len, n_feats):
    if name == 'Transformer': return build_transformer_model(seq_len, n_feats)
    if name == 'LSTM':       return build_lstm_model(seq_len, n_feats)
    if name == 'RNN':        return build_rnn_model(seq_len, n_feats)
    raise ValueError(name)

EPOCHS = 50
BATCH_SIZE = 32
EARLY_STOP = callbacks.EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)


def concat_overall(processed_data_dict, sectors):
    Xs, ys = [], []
    for s in sectors:
        if s in processed_data_dict:
            Xs.append(processed_data_dict[s]['X'])
            ys.append(ensure_targets_column(processed_data_dict[s]['y']))
    return np.concatenate(Xs, 0), np.concatenate(ys, 0)

# Re-run the OVERALL training part to define the variables
X_all, y_all = concat_overall(processed_data_dict, sectors)
seq_len_all, n_feats_all = X_all.shape[1], X_all.shape[2]

# Perform the split again if X_all is not empty
if len(X_all) > 0:
  Xtr_all, ytr_all, Xv_all, yv_all, Xte_all, yte_all = ts_split(X_all, y_all, 0.8, 0.1)
  print(f"OVERALL (re-computed): Train {Xtr_all.shape}, Val {Xv_all.shape}, Test {Xte_all.shape}")

  model_histories_overall = {}
  all_results_overall = {}

  for model_type in MODEL_TYPES:
      print(f"\n=== OVERALL {model_type} (re-training) ===")
      model = build_model_by_name(model_type, seq_len_all, n_feats_all)
      hist = model.fit(
          Xtr_all, ytr_all,
          validation_data=(Xv_all, yv_all),
          epochs=EPOCHS, batch_size=BATCH_SIZE, verbose=1,
          callbacks=[EARLY_STOP]
      )
      model_histories_overall[model_type] = hist

      mse, mae = model.evaluate(Xte_all, yte_all, verbose=0)
      all_results_overall[model_type] = {"Test_MSE": float(mse), "Test_MAE": float(mae)}

      # Save model - using the same path as Block 6b
      path = os.path.join(OUTPUT_MODELS_DIR, f"{model_type}_model_OVERALL.keras")
      model.save(path)
      print(f"Saved OVERALL (re-trained) → {path} | Test MSE={mse:.6f} MAE={mae:.6f}")
else:
    # Handle the case where X_all is empty (e.g., no sectors processed)
    print("No data to process for OVERALL model.")
    model_histories_overall = {}
    all_results_overall = {}


# --- Original code from Block 7 starts here ---

def last_or_nan(x):
    return float(x[-1]) if isinstance(x, (list, tuple)) and len(x) else (float(x) if np.ndim(x)==0 else np.nan)

def hist_to_row(hist, model_type, sector):
    h = hist.history
    return {
        "Model": model_type,
        "Sector": sector,
        "Train_MSE_last": last_or_nan(h.get('loss', [])),
        "Val_MSE_last":   last_or_nan(h.get('val_loss', [])),
        "Train_MAE_last": last_or_nan(h.get('mae', [])),
        "Val_MAE_last":   last_or_nan(h.get('val_mae', [])),
    }

# Per-sector table
rows = []
for model_type in MODEL_TYPES:
    for sector in sectors:
        # Use model_histories which should be defined from Block 6
        hist = model_histories.get(model_type, {}).get(sector)
        if hist is None:
            continue
        row = hist_to_row(hist, model_type, sector)
        # Use all_results which should be defined from Block 6
        res = all_results.get(model_type, {}).get(sector, {})
        row["Test_RMSE_Actual_Return"] = res.get("RMSE_Actual_Return", np.nan)
        row["Test_MAE_Actual_Return"]  = res.get("MAE_Actual_Return",  np.nan)
        rows.append(row)
df_per_sector = pd.DataFrame(rows).sort_values(["Model", "Sector"])
display(df_per_sector.head(12))

# OVERALL table
rows_overall = []
for model_type, hist in model_histories_overall.items():
    row = hist_to_row(hist, model_type, "OVERALL")
    test = all_results_overall.get(model_type, {})
    row["Test_MSE"] = test.get("Test_MSE", np.nan)
    row["Test_MAE"] = test.get("Test_MAE", np.nan)
    rows_overall.append(row)
df_overall = pd.DataFrame(rows_overall).sort_values(["Model"])
display(df_overall)

# Save CSVs
per_sector_csv = os.path.join(OUTPUT_RESULTS_DIR, "comparison_per_sector.csv")
overall_csv    = os.path.join(OUTPUT_RESULTS_DIR, "comparison_overall.csv")
df_per_sector.to_csv(per_sector_csv, index=False)
df_overall.to_csv(overall_csv, index=False)
print("Saved:", per_sector_csv)
print("Saved:", overall_csv)

OVERALL (re-computed): Train (3379, 8, 5), Val (422, 8, 5), Test (423, 8, 5)

=== OVERALL Transformer (re-training) ===
Epoch 1/50
106/106 ━━━━━━━━━━━━━━━━━━━━ 7s 11ms/step - loss: 0.0463 - mae: 0.1593 - val_loss: 0.0099 - val_mae: 0.0644
Epoch 2/50
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0117 - mae: 0.0794 - val_loss: 0.0073 - val_mae: 0.0327
Epoch 3/50
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0096 - mae: 0.0703 - val_loss: 0.0073 - val_mae: 0.0296
Epoch 4/50
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0095 - mae: 0.0699 - val_loss: 0.0082 - val_mae: 0.0356
Epoch 5/50
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0081 - mae: 0.0635 - val_loss: 0.0074 - val_mae: 0.0356
Epoch 6/50
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0078 - mae: 0.0623 - val_loss: 0.0082 - val_mae: 0.0320
Epoch 7/50
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0084 - mae: 0.0633 - val_loss: 0.0078 - val_mae: 0.0341
Epoch 8/50
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0073 - mae: 0.0599 - val_loss: 0.0083 - val_mae: 0.0389
Saved OVERALL (re-trained) → /content/drive/MyDrive/AML /All/models_1/Transformer_model_OVERALL.keras | Test MSE=0.002334 MAE=0.021772

=== OVERALL LSTM (re-training) ===
Epoch 1/50
106/106 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - loss: 0.0406 - mae: 0.1420 - val_loss: 0.0069 - val_mae: 0.0374
Epoch 2/50
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0087 - mae: 0.0658 - val_loss: 0.0067 - val_mae: 0.0324
Epoch 3/50
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0076 - mae: 0.0615 - val_loss: 0.0074 - val_mae: 0.0441
Epoch 4/50
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0074 - mae: 0.0608 - val_loss: 0.0070 - val_mae: 0.0360
Epoch 5/50
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0071 - mae: 0.0587 - val_loss: 0.0073 - val_mae: 0.0399
Epoch 6/50
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0072 - mae: 0.0582 - val_loss: 0.0072 - val_mae: 0.0372
Epoch 7/50
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0069 - mae: 0.0572 - val_loss: 0.0075 - val_mae: 0.0408
Saved OVERALL (re-trained) → /content/drive/MyDrive/AML /All/models_1/LSTM_model_OVERALL.keras | Test MSE=0.002140 MAE=0.023368

=== OVERALL RNN (re-training) ===
Epoch 1/50
106/106 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 0.0586 - mae: 0.1602 - val_loss: 0.0076 - val_mae: 0.0448
Epoch 2/50
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0092 - mae: 0.0681 - val_loss: 0.0081 - val_mae: 0.0488
Epoch 3/50
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0084 - mae: 0.0673 - val_loss: 0.0074 - val_mae: 0.0384
Epoch 4/50
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0079 - mae: 0.0650 - val_loss: 0.0074 - val_mae: 0.0353
Epoch 5/50
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 0.0084 - mae: 0.0654 - val_loss: 0.0077 - val_mae: 0.0361
Epoch 6/50
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0075 - mae: 0.0609 - val_loss: 0.0075 - val_mae: 0.0343
Epoch 7/50
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0070 - mae: 0.0585 - val_loss: 0.0076 - val_mae: 0.0346
Epoch 8/50
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0069 - mae: 0.0576 - val_loss: 0.0082 - val_mae: 0.0460
Epoch 9/50
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0063 - mae: 0.0550 - val_loss: 0.0077 - val_mae: 0.0349
Saved OVERALL (re-trained) → /content/drive/MyDrive/AML /All/models_1/RNN_model_OVERALL.keras | Test MSE=0.002307 MAE=0.026065

,Model,Sector,Train_MSE_last,Val_MSE_last,Train_MAE_last,Val_MAE_last,Test_RMSE_Actual_Return,Test_MAE_Actual_Return
5,LSTM,Engineering,0.007770,0.002285,0.060160,0.032758,0.780778,0.515608
6,LSTM,Fuel & Power,0.009558,0.006399,0.069702,0.051481,1.658904,1.312094
7,LSTM,IT Sector,0.008394,0.004586,0.064855,0.051755,0.276484,0.191973
8,LSTM,Services & Real Estate,0.005780,0.000536,0.056911,0.020556,0.441165,0.306835
9,LSTM,Telecommunication,0.007955,0.002468,0.055460,0.031768,1.203033,0.621188
10,RNN,Engineering,0.007671,0.003036,0.061520,0.040372,0.842759,0.577248
11,RNN,Fuel & Power,0.009324,0.005762,0.067598,0.045195,1.464325,1.185529
12,RNN,IT Sector,0.008857,0.004422,0.068247,0.050619,0.278020,0.181631
13,RNN,Services & Real Estate,0.003573,0.001046,0.041115,0.027705,0.602634,0.433935
14,RNN,Telecommunication,0.008041,0.002450,0.056941,0.031305,1.113397,0.633615
0,Transformer,Engineering,0.012894,0.005245,0.080600,0.063103,0.921756,0.684283
1,Transformer,Fuel & Power,0.013269,0.009793,0.083596,0.076844,1.668649,1.308134

,Model,Sector,Train_MSE_last,Val_MSE_last,Train_MAE_last,Val_MAE_last,Test_MSE,Test_MAE
1,LSTM,OVERALL,0.00690,0.007461,0.056770,0.040802,0.002140,0.023368
2,RNN,OVERALL,0.00656,0.007686,0.055662,0.034894,0.002307,0.026065
0,Transformer,OVERALL,0.00760,0.008274,0.060199,0.038852,0.002334,0.021772

Saved: /content/drive/MyDrive/AML /All/results_/comparison_per_sector.csv
Saved: /content/drive/MyDrive/AML /All/results_/comparison_overall.csv

In [ ]:
# Block 8: Graphs — Loss/MAE (Per-Sector & OVERALL) + Predictions & Sector Bars

def plot_loss_mae(history, title_prefix, base_name):
    # Loss
    plt.figure()
    plt.plot(history.history.get('loss', []), label='Train Loss')
    plt.plot(history.history.get('val_loss', []), label='Val Loss')
    plt.title(f"{title_prefix} — Loss")
    plt.xlabel("Epoch"); plt.ylabel("MSE"); plt.legend(); plt.tight_layout()
    p = os.path.join(OUTPUT_FIGURES_DIR, f"{base_name}_loss.png"); plt.savefig(p, dpi=160); plt.close()

    # MAE
    plt.figure()
    plt.plot(history.history.get('mae', []), label='Train MAE')
    plt.plot(history.history.get('val_mae', []), label='Val MAE')
    plt.title(f"{title_prefix} — MAE")
    plt.xlabel("Epoch"); plt.ylabel("MAE"); plt.legend(); plt.tight_layout()
    p = os.path.join(OUTPUT_FIGURES_DIR, f"{base_name}_mae.png"); plt.savefig(p, dpi=160); plt.close()

def plot_pred_vs_actual(actual, pred, title_prefix, base_name, num_points=None):
    a = actual if num_points is None else actual[-num_points:]
    p = pred   if num_points is None else pred[-num_points:]
    plt.figure()
    plt.plot(a, label="Actual")
    plt.plot(p, label="Predicted")
    plt.title(f"{title_prefix} — Prediction vs Actual")
    plt.xlabel("Time"); plt.ylabel("Price"); plt.legend(); plt.tight_layout()
    path = os.path.join(OUTPUT_FIGURES_DIR, f"{base_name}_pred_vs_actual.png")
    plt.savefig(path, dpi=160); plt.close()

def plot_zoom(actual, pred, title_prefix, base_name, start=-150, end=None):
    a = actual[start:end]; p = pred[start:end]
    plt.figure()
    plt.plot(a, label="Actual"); plt.plot(p, label="Predicted")
    plt.title(f"{title_prefix} — Zoom")
    plt.xlabel("Time"); plt.ylabel("Price"); plt.legend(); plt.tight_layout()
    path = os.path.join(OUTPUT_FIGURES_DIR, f"{base_name}_zoom.png")
    plt.savefig(path, dpi=160); plt.close()

def bar_by_sector(metric_name, model_type, results_dict, suffix):
    sectors_list, vals = [], []
    for s in sectors:
        if s in results_dict.get(model_type, {}):
            sectors_list.append(s)
            vals.append(results_dict[model_type][s][metric_name])
    if not sectors_list: return
    plt.figure(figsize=(10,4.5))
    plt.bar(range(len(vals)), vals)
    plt.xticks(range(len(vals)), sectors_list, rotation=45, ha='right')
    plt.ylabel(metric_name.replace('_', ' ')); plt.title(f"{model_type} — {metric_name} across sectors")
    plt.tight_layout()
    path = os.path.join(OUTPUT_FIGURES_DIR, f"{model_type}_{suffix}_{metric_name}.png")
    plt.savefig(path, dpi=160); plt.close()

# Per-sector: curves and predictions
for model_type in MODEL_TYPES:
    for s in sectors:
        hist = model_histories.get(model_type, {}).get(s)
        if hist is None:
            continue
        base = f"{model_type}_{s.replace(' ', '_')}"
        plot_loss_mae(hist, f"{model_type} | {s}", base)

        res = all_results.get(model_type, {}).get(s, {})
        predicted_prices = res.get('predicted_closing_prices')
        actual_prices = res.get('actual_closing_prices')

        if predicted_prices is not None and actual_prices is not None and len(predicted_prices) > 0:
            plot_pred_vs_actual(actual_prices, predicted_prices,
                                f"{model_type} | {s}", base)
            plot_zoom(actual_prices, predicted_prices,
                      f"{model_type} | {s}", base)

# OVERALL: curves
for model_type, hist in model_histories_overall.items():
    base = f"{model_type}_OVERALL"
    plot_loss_mae(hist, f"{model_type} | OVERALL", base)

# Aggregate bars across sectors
for model_type in MODEL_TYPES:
    bar_by_sector('RMSE_Actual_Return', model_type, all_results, 'Test')
    bar_by_sector('MAE_Actual_Return',  model_type, all_results, 'Test')

print("Saved: per-sector Loss/MAE, OVERALL Loss/MAE, per-sector Pred vs Actual (with zoom), and sector bar charts.")

Saved: per-sector Loss/MAE, OVERALL Loss/MAE, per-sector Pred vs Actual (with zoom), and sector bar charts.

In [ ]:
# Block 9: Utility — quick glance

print("Comparison CSVs:")
print(os.path.join(OUTPUT_RESULTS_DIR, "comparison_per_sector.csv"))
print(os.path.join(OUTPUT_RESULTS_DIR, "comparison_overall.csv"))

print("\nExample figure paths:")
for m in MODEL_TYPES:
    print(os.path.join(OUTPUT_FIGURES_DIR, f"{m}_OVERALL_loss.png"))
    print(os.path.join(OUTPUT_FIGURES_DIR, f"{m}_OVERALL_mae.png"))

Comparison CSVs:
/content/drive/MyDrive/AML /All/results/comparison_per_sector.csv
/content/drive/MyDrive/AML /All/results/comparison_overall.csv

Example figure paths:
/content/drive/MyDrive/AML /All/figures/Transformer_OVERALL_loss.png
/content/drive/MyDrive/AML /All/figures/Transformer_OVERALL_mae.png
/content/drive/MyDrive/AML /All/figures/LSTM_OVERALL_loss.png
/content/drive/MyDrive/AML /All/figures/LSTM_OVERALL_mae.png
/content/drive/MyDrive/AML /All/figures/RNN_OVERALL_loss.png
/content/drive/MyDrive/AML /All/figures/RNN_OVERALL_mae.png

In [ ]:
'''
# Block 10: Real-world testing on unseen market data (paper-style)

# Put a fresh CSV with columns:
#   sector, trading date, open, high, low, close, volume
REAL_WORLD_CSV   = '.csv'  # update with your unseen data file
REAL_RESULTS_CSV = os.path.join(OUTPUT_RESULTS_DIR, "realworld_comparison.csv")
REAL_FIG_DIR     = os.path.join(OUTPUT_FIGURES_DIR, "realworld")
os.makedirs(REAL_FIG_DIR, exist_ok=True)

def _normalize_columns(df_):
    df_ = df_.copy()
    df_.columns = df_.columns.str.strip()
    if 'trading date' not in df_.columns:
        for k in ['trading_date', 'date', 'Trading Date', 'Trading date']:
            if k in df_.columns:
                df_['trading date'] = df_[k]
                break
    df_['trading date'] = pd.to_datetime(df_['trading date'], errors='coerce')
    df_ = df_.dropna(subset=['trading date']).sort_values(['sector', 'trading date'])
    return df_

def _make_stationary_returns(g):
    g = g.copy()
    smooth = g[FEATURES].rolling(window=10, min_periods=1).mean()
    for c in FEATURES:
        g[f'return_{c}'] = smooth[c].diff()
    g = g.dropna().reset_index(drop=True)
    return g

def _apply_training_scaler(g, sector_name):
    pkl = os.path.join(SCALERS_DIR, f"scaler_{sector_name.replace(' ', '_')}.pkl")
    if not os.path.exists(pkl):
        raise FileNotFoundError(f"Saved scaler not found for sector {sector_name}: {pkl}")
    scaler = joblib.load(pkl)
    g[RET_COLS] = scaler.transform(g[RET_COLS])
    return g, scaler

def _create_sequences_for_inference(data_df, seq_len=SEQ_LEN):
    X, last_closes, idx_map = [], [], []
    for i in range(seq_len, len(data_df)):
        X.append(data_df[RET_COLS].iloc[i-seq_len:i].values)
        last_closes.append(data_df['close'].iloc[i-1])
        idx_map.append(i)
    return np.array(X), np.array(last_closes), np.array(idx_map)

def _reconstruct_prices(last_closes, pred_returns, true_returns):
    pred_prices = last_closes + pred_returns
    true_prices = last_closes + true_returns
    return pred_prices, true_prices

def _predict_with_model(model_path, X):
    model = tf.keras.models.load_model(model_path, compile=False)
    model.compile(optimizer="adam", loss="mse", metrics=["mae"])
    y_pred = model.predict(X, verbose=0).reshape(-1)
    return y_pred

def _plot_realworld(actual_prices, predicted_prices, title, base):
    # Full
    plt.figure()
    plt.plot(actual_prices, label="Actual")
    plt.plot(predicted_prices, label="Predicted")
    plt.title(f"{title} — Real-world")
    plt.xlabel("Time"); plt.ylabel("Price"); plt.legend(); plt.tight_layout()
    p = os.path.join(REAL_FIG_DIR, f"{base}_realworld.png")
    plt.savefig(p, dpi=160); plt.close()

    # Zoom (tail)
    z = min(150, len(actual_prices))
    plt.figure()
    plt.plot(actual_prices[-z:], label="Actual")
    plt.plot(predicted_prices[-z:], label="Predicted")
    plt.title(f"{title} — Real-world (zoom last {z})")
    plt.xlabel("Time"); plt.ylabel("Price"); plt.legend(); plt.tight_layout()
    p = os.path.join(REAL_FIG_DIR, f"{base}_realworld_zoom.png")
    plt.savefig(p, dpi=160); plt.close()

# Load real-world data
real_df = pd.read_csv(REAL_WORLD_CSV)
real_df = _normalize_columns(real_df)

rows = []

# Per-sector real-world test
for sector in sectors:
    sec_df = real_df[real_df['sector'] == sector].copy()
    if len(sec_df) < SEQ_LEN + 5:
        print(f"[Real] Skipping {sector}: too few rows ({len(sec_df)})")
        continue

    sec_proc = _make_stationary_returns(sec_df)
    try:
        sec_proc, scaler = _apply_training_scaler(sec_proc, sector)
    except FileNotFoundError as e:
        print(e)
        continue

    X_inf, last_closes_inf, idx_map = _create_sequences_for_inference(sec_proc, SEQ_LEN)
    y_true_norm = sec_proc['return_close'].iloc[idx_map].values

    close_idx = RET_COLS.index('return_close')
    def invert_close_only(arr_norm_1d):
        dummy = np.zeros((len(arr_norm_1d), len(RET_COLS)))
        dummy[:, close_idx] = arr_norm_1d
        inv = scaler.inverse_transform(dummy)
        return inv[:, close_idx]

    y_true_ret = invert_close_only(y_true_norm)

    for model_type in MODEL_TYPES:
        model_path = os.path.join(OUTPUT_MODELS_DIR, f"{model_type}_model_{sector.replace(' ', '_')}.keras")
        if not os.path.exists(model_path):
            print(f"[Real] Missing model: {model_path}")
            continue

        y_pred_norm = _predict_with_model(model_path, X_inf)
        y_pred_ret  = invert_close_only(y_pred_norm)

        pred_px, true_px = _reconstruct_prices(last_closes_inf, y_pred_ret, y_true_ret)
        rmse = np.sqrt(mean_squared_error(true_px, pred_px))
        mae  = mean_absolute_error(true_px, pred_px)

        rows.append({
            "Scope": "Per-Sector",
            "Sector": sector,
            "Model": model_type,
            "RMSE_RealPrice": float(rmse),
            "MAE_RealPrice":  float(mae),
            "N": len(true_px)
        })

        base = f"{model_type}_{sector.replace(' ', '_')}"
        _plot_realworld(true_px, pred_px, f"{model_type} | {sector}", base)

# OVERALL real-world test (pooled)
X_all, y_all_ret, last_all, pairs = [], [], [], []
for sector in sectors:
    sec_df = real_df[real_df['sector'] == sector].copy()
    if len(sec_df) < SEQ_LEN + 5:
        continue
    sec_proc = _make_stationary_returns(sec_df)
    try:
        sec_proc, scaler = _apply_training_scaler(sec_proc, sector)
    except FileNotFoundError:
        continue
    X_inf, last_inf, idx_map = _create_sequences_for_inference(sec_proc, SEQ_LEN)
    y_true_norm = sec_proc['return_close'].iloc[idx_map].values

    close_idx = RET_COLS.index('return_close')
    def inv_close(arr_norm_1d):
        dummy = np.zeros((len(arr_norm_1d), len(RET_COLS)))
        dummy[:, close_idx] = arr_norm_1d
        inv = scaler.inverse_transform(dummy)
        return inv[:, close_idx]

    y_true_ret = inv_close(y_true_norm)

    X_all.append(X_inf); y_all_ret.append(y_true_ret); last_all.append(last_inf)
    pairs.append((sector, len(X_inf)))

if len(X_all):
    X_all = np.concatenate(X_all, axis=0)
    y_all_ret = np.concatenate(y_all_ret, axis=0)
    last_all  = np.concatenate(last_all, axis=0)

    for model_type in MODEL_TYPES:
        overall_path = os.path.join(OUTPUT_MODELS_DIR, f"{model_type}_model_OVERALL.keras")
        if not os.path.exists(overall_path):
            print(f"[Real] Missing OVERALL model: {overall_path}")
            continue

        y_pred_norm = _predict_with_model(overall_path, X_all)

        # Convert predicted returns into actual units per-window using each sector's scaler
        pred_ret_actual = np.empty_like(y_pred_norm, dtype=float)
        cursor = 0
        for sector, count in pairs:
            scaler = joblib.load(os.path.join(SCALERS_DIR, f"scaler_{sector.replace(' ', '_')}.pkl"))
            seg = y_pred_norm[cursor:cursor+count]
            close_idx = RET_COLS.index('return_close')
            dummy = np.zeros((len(seg), len(RET_COLS)))
            dummy[:, close_idx] = seg
            inv = scaler.inverse_transform(dummy)
            pred_ret_actual[cursor:cursor+count] = inv[:, close_idx]
            cursor += count

        pred_px, true_px = _reconstruct_prices(last_all, pred_ret_actual, y_all_ret)
        rmse = np.sqrt(mean_squared_error(true_px, pred_px))
        mae  = mean_absolute_error(true_px, pred_px)

        rows.append({
            "Scope": "OVERALL",
            "Sector": "ALL",
            "Model": model_type,
            "RMSE_RealPrice": float(rmse),
            "MAE_RealPrice":  float(mae),
            "N": len(true_px)
        })

        tail = min(1000, len(true_px))
        plt.figure()
        plt.plot(true_px[-tail:], label="Actual")
        plt.plot(pred_px[-tail:], label="Predicted")
        plt.title(f"{model_type} | OVERALL — Real-world (tail {tail})")
        plt.xlabel("Time"); plt.ylabel("Price"); plt.legend(); plt.tight_layout()
        p = os.path.join(REAL_FIG_DIR, f"{model_type}_OVERALL_realworld_tail.png")
        plt.savefig(p, dpi=160); plt.close()

# Save the real-world comparison table
df_realworld = pd.DataFrame(rows).sort_values(["Scope", "Model", "Sector"])
df_realworld.to_csv(REAL_RESULTS_CSV, index=False)
print("Saved real-world comparison:", REAL_RESULTS_CSV)
display(df_realworld.head(20))
'''

'\n# Block 10: Real-world testing on unseen market data (paper-style)\n\n# Put a fresh CSV with columns:\n#   sector, trading date, open, high, low, close, volume\nREAL_WORLD_CSV   = \'.csv\'  # update with your unseen data file\nREAL_RESULTS_CSV = os.path.join(OUTPUT_RESULTS_DIR, "realworld_comparison.csv")\nREAL_FIG_DIR     = os.path.join(OUTPUT_FIGURES_DIR, "realworld")\nos.makedirs(REAL_FIG_DIR, exist_ok=True)\n\ndef _normalize_columns(df_):\n    df_ = df_.copy()\n    df_.columns = df_.columns.str.strip()\n    if \'trading date\' not in df_.columns:\n        for k in [\'trading_date\', \'date\', \'Trading Date\', \'Trading date\']:\n            if k in df_.columns:\n                df_[\'trading date\'] = df_[k]\n                break\n    df_[\'trading date\'] = pd.to_datetime(df_[\'trading date\'], errors=\'coerce\')\n    df_ = df_.dropna(subset=[\'trading date\']).sort_values([\'sector\', \'trading date\'])\n    return df_\n\ndef _make_stationary_returns(g):\n    g = g.copy()\n    smooth = g[FEATURES].rolling(window=10, min_periods=1).mean()\n    for c in FEATURES:\n        g[f\'return_{c}\'] = smooth[c].diff()\n    g = g.dropna().reset_index(drop=True)\n    return g\n\ndef _apply_training_scaler(g, sector_name):\n    pkl = os.path.join(SCALERS_DIR, f"scaler_{sector_name.replace(\' \', \'_\')}.pkl")\n    if not os.path.exists(pkl):\n        raise FileNotFoundError(f"Saved scaler not found for sector {sector_name}: {pkl}")\n    scaler = joblib.load(pkl)\n    g[RET_COLS] = scaler.transform(g[RET_COLS])\n    return g, scaler\n\ndef _create_sequences_for_inference(data_df, seq_len=SEQ_LEN):\n    X, last_closes, idx_map = [], [], []\n    for i in range(seq_len, len(data_df)):\n        X.append(data_df[RET_COLS].iloc[i-seq_len:i].values)\n        last_closes.append(data_df[\'close\'].iloc[i-1])\n        idx_map.append(i)\n    return np.array(X), np.array(last_closes), np.array(idx_map)\n\ndef _reconstruct_prices(last_closes, pred_returns, true_returns):\n    pred_prices = last_closes + pred_returns\n    true_prices = last_closes + true_returns\n    return pred_prices, true_prices\n\ndef _predict_with_model(model_path, X):\n    model = tf.keras.models.load_model(model_path, compile=False)\n    model.compile(optimizer="adam", loss="mse", metrics=["mae"])\n    y_pred = model.predict(X, verbose=0).reshape(-1)\n    return y_pred\n\ndef _plot_realworld(actual_prices, predicted_prices, title, base):\n    # Full\n    plt.figure()\n    plt.plot(actual_prices, label="Actual")\n    plt.plot(predicted_prices, label="Predicted")\n    plt.title(f"{title} — Real-world")\n    plt.xlabel("Time"); plt.ylabel("Price"); plt.legend(); plt.tight_layout()\n    p = os.path.join(REAL_FIG_DIR, f"{base}_realworld.png")\n    plt.savefig(p, dpi=160); plt.close()\n\n    # Zoom (tail)\n    z = min(150, len(actual_prices))\n    plt.figure()\n    plt.plot(actual_prices[-z:], label="Actual")\n    plt.plot(predicted_prices[-z:], label="Predicted")\n    plt.title(f"{title} — Real-world (zoom last {z})")\n    plt.xlabel("Time"); plt.ylabel("Price"); plt.legend(); plt.tight_layout()\n    p = os.path.join(REAL_FIG_DIR, f"{base}_realworld_zoom.png")\n    plt.savefig(p, dpi=160); plt.close()\n\n# Load real-world data\nreal_df = pd.read_csv(REAL_WORLD_CSV)\nreal_df = _normalize_columns(real_df)\n\nrows = []\n\n# Per-sector real-world test\nfor sector in sectors:\n    sec_df = real_df[real_df[\'sector\'] == sector].copy()\n    if len(sec_df) < SEQ_LEN + 5:\n        print(f"[Real] Skipping {sector}: too few rows ({len(sec_df)})")\n        continue\n\n    sec_proc = _make_stationary_returns(sec_df)\n    try:\n        sec_proc, scaler = _apply_training_scaler(sec_proc, sector)\n    except FileNotFoundError as e:\n        print(e)\n        continue\n\n    X_inf, last_closes_inf, idx_map = _create_sequences_for_inference(sec_proc, SEQ_LEN)\n    y_true_norm = sec_proc[\'return_close\'].iloc[idx_map].values\n\n    close_idx = RET_COLS.index(\'return_close\')\n    def invert_close_only(arr_norm_1d):\n        dummy = np.zeros((len(arr_norm_1d), len(RET_COLS)))\n        dummy[:, close_idx] = arr_norm_1d\n        inv = scaler.inverse_transform(dummy)\n        return inv[:, close_idx]\n\n    y_true_ret = invert_close_only(y_true_norm)\n\n    for model_type in MODEL_TYPES:\n        model_path = os.path.join(OUTPUT_MODELS_DIR, f"{model_type}_model_{sector.replace(\' \', \'_\')}.keras")\n        if not os.path.exists(model_path):\n            print(f"[Real] Missing model: {model_path}")\n            continue\n\n        y_pred_norm = _predict_with_model(model_path, X_inf)\n        y_pred_ret  = invert_close_only(y_pred_norm)\n\n        pred_px, true_px = _reconstruct_prices(last_closes_inf, y_pred_ret, y_true_ret)\n        rmse = np.sqrt(mean_squared_error(true_px, pred_px))\n        mae  = mean_absolute_error(true_px, pred_px)\n\n        rows.append({\n            "Scope": "Per-Sector",\n            "Sector": sector,\n            "Model": model_type,\n            "RMSE_RealPrice": float(rmse),\n            "MAE_RealPrice":  float(mae),\n            "N": len(true_px)\n        })\n\n        base = f"{model_type}_{sector.replace(\' \', \'_\')}"\n        _plot_realworld(true_px, pred_px, f"{model_type} | {sector}", base)\n\n# OVERALL real-world test (pooled)\nX_all, y_all_ret, last_all, pairs = [], [], [], []\nfor sector in sectors:\n    sec_df = real_df[real_df[\'sector\'] == sector].copy()\n    if len(sec_df) < SEQ_LEN + 5: \n        continue\n    sec_proc = _make_stationary_returns(sec_df)\n    try:\n        sec_proc, scaler = _apply_training_scaler(sec_proc, sector)\n    except FileNotFoundError:\n        continue\n    X_inf, last_inf, idx_map = _create_sequences_for_inference(sec_proc, SEQ_LEN)\n    y_true_norm = sec_proc[\'return_close\'].iloc[idx_map].values\n\n    close_idx = RET_COLS.index(\'return_close\')\n    def inv_close(arr_norm_1d):\n        dummy = np.zeros((len(arr_norm_1d), len(RET_COLS)))\n        dummy[:, close_idx] = arr_norm_1d\n        inv = scaler.inverse_transform(dummy)\n        return inv[:, close_idx]\n\n    y_true_ret = inv_close(y_true_norm)\n\n    X_all.append(X_inf); y_all_ret.append(y_true_ret); last_all.append(last_inf)\n    pairs.append((sector, len(X_inf)))\n\nif len(X_all):\n    X_all = np.concatenate(X_all, axis=0)\n    y_all_ret = np.concatenate(y_all_ret, axis=0)\n    last_all  = np.concatenate(last_all, axis=0)\n\n    for model_type in MODEL_TYPES:\n        overall_path = os.path.join(OUTPUT_MODELS_DIR, f"{model_type}_model_OVERALL.keras")\n        if not os.path.exists(overall_path):\n            print(f"[Real] Missing OVERALL model: {overall_path}")\n            continue\n\n        y_pred_norm = _predict_with_model(overall_path, X_all)\n\n        # Convert predicted returns into actual units per-window using each sector\'s scaler\n        pred_ret_actual = np.empty_like(y_pred_norm, dtype=float)\n        cursor = 0\n        for sector, count in pairs:\n            scaler = joblib.load(os.path.join(SCALERS_DIR, f"scaler_{sector.replace(\' \', \'_\')}.pkl"))\n            seg = y_pred_norm[cursor:cursor+count]\n            close_idx = RET_COLS.index(\'return_close\')\n            dummy = np.zeros((len(seg), len(RET_COLS)))\n            dummy[:, close_idx] = seg\n            inv = scaler.inverse_transform(dummy)\n            pred_ret_actual[cursor:cursor+count] = inv[:, close_idx]\n            cursor += count\n\n        pred_px, true_px = _reconstruct_prices(last_all, pred_ret_actual, y_all_ret)\n        rmse = np.sqrt(mean_squared_error(true_px, pred_px))\n        mae  = mean_absolute_error(true_px, pred_px)\n\n        rows.append({\n            "Scope": "OVERALL",\n            "Sector": "ALL",\n            "Model": model_type,\n            "RMSE_RealPrice": float(rmse),\n            "MAE_RealPrice":  float(mae),\n            "N": len(true_px)\n        })\n\n        tail = min(1000, len(true_px))\n        plt.figure()\n        plt.plot(true_px[-tail:], label="Actual")\n        plt.plot(pred_px[-tail:], label="Predicted")\n        plt.title(f"{model_type} | OVERALL — Real-world (tail {tail})")\n        plt.xlabel("Time"); plt.ylabel("Price"); plt.legend(); plt.tight_layout()\n        p = os.path.join(REAL_FIG_DIR, f"{model_type}_OVERALL_realworld_tail.png")\n        plt.savefig(p, dpi=160); plt.close()\n\n# Save the real-world comparison table\ndf_realworld = pd.DataFrame(rows).sort_values(["Scope", "Model", "Sector"])\ndf_realworld.to_csv(REAL_RESULTS_CSV, index=False)\nprint("Saved real-world comparison:", REAL_RESULTS_CSV)\ndisplay(df_realworld.head(20))\n'

In [ ]:
# Block 11: Paper-style Processed vs Raw plots (per sector & model

PAPER_FIG_DIR = os.path.join(OUTPUT_FIGURES_DIR, "paper_style")
os.makedirs(PAPER_FIG_DIR, exist_ok=True)

def _reload_model(model_type, sector):
    path = os.path.join(OUTPUT_MODELS_DIR, f"{model_type}_model_{sector.replace(' ', '_')}.keras")
    if not os.path.exists(path):
        print(f"[Block11] Missing model file: {path}")
        return None, path
    # Allow unsafe deserialization for the Lambda layer with a Python lambda
    m = tf.keras.models.load_model(path, compile=False, safe_mode=False)
    m.compile(optimizer="adam", loss="mse", metrics=["mae"])
    return m, path

def _sector_split_again(sector):
    """Recreate the exact 80/10/10 split used in training for this sector."""
    pack = processed_data_dict[sector]
    X = pack['X']
    y = pack['y'].reshape(-1, 1) if np.ndim(pack['y']) == 1 else pack['y']
    Xtr, ytr, Xv, yv, Xte, yte = ts_split(X, y, 0.8, 0.1)
    last_closes = pack['last_closes']
    last_closes_test = last_closes[len(ytr) + len(yv):]
    scaler = scalers[sector]
    return Xtr, ytr, Xv, yv, Xte, yte, last_closes_test, scaler

def _invert_close_only(scaler, ret_norm):
    """Invert only the close-return dimension back to actual units."""
    close_idx = RET_COLS.index('return_close')
    dummy = np.zeros((len(ret_norm), len(RET_COLS)))
    dummy[:, close_idx] = ret_norm
    inv = scaler.inverse_transform(dummy)
    return inv[:, close_idx]

def _plot_processed_returns(y_true_norm, y_pred_norm, title_prefix, base):
    # Full processed comparison (normalized returns)
    plt.figure()
    plt.plot(y_true_norm, label="True (processed)")
    plt.plot(y_pred_norm, label="Pred (processed)")
    plt.title(f"{title_prefix} — Processed (returns)")
    plt.xlabel("Test index"); plt.ylabel("Normalized return")
    plt.legend(); plt.tight_layout()
    p = os.path.join(PAPER_FIG_DIR, f"{base}_processed_returns.png")
    plt.savefig(p, dpi=170); plt.close()

    # Zoom tail
    z = min(150, len(y_true_norm))
    plt.figure()
    plt.plot(y_true_norm[-z:], label="True (processed)")
    plt.plot(y_pred_norm[-z:], label="Pred (processed)")
    plt.title(f"{title_prefix} — Processed (returns) zoom last {z}")
    plt.xlabel("Test index (tail)"); plt.ylabel("Normalized return")
    plt.legend(); plt.tight_layout()
    p = os.path.join(PAPER_FIG_DIR, f"{base}_processed_returns_zoom.png")
    plt.savefig(p, dpi=170); plt.close()

def _plot_raw_prices(actual_px, pred_px, title_prefix, base):
    # Full raw price comparison
    plt.figure()
    plt.plot(actual_px, label="Actual price")
    plt.plot(pred_px, label="Predicted price")
    plt.title(f"{title_prefix} — Raw closing price")
    plt.xlabel("Test index"); plt.ylabel("Price")
    plt.legend(); plt.tight_layout()
    p = os.path.join(PAPER_FIG_DIR, f"{base}_raw_prices.png")
    plt.savefig(p, dpi=170); plt.close()

    # Zoom tail
    z = min(150, len(actual_px))
    plt.figure()
    plt.plot(actual_px[-z:], label="Actual price")
    plt.plot(pred_px[-z:], label="Predicted price")
    plt.title(f"{title_prefix} — Raw price (zoom last {z})")
    plt.xlabel("Test index (tail)"); plt.ylabel("Price")
    plt.legend(); plt.tight_layout()
    p = os.path.join(PAPER_FIG_DIR, f"{base}_raw_prices_zoom.png")
    plt.savefig(p, dpi=170); plt.close()

# --- Generate paired plots for every (model × sector) ---
for model_type in MODEL_TYPES:
    for sector in sectors:
        if sector not in processed_data_dict:
            continue

        # Reload model & recreate split
        model, model_path = _reload_model(model_type, sector)
        if model is None:
            continue
        Xtr, ytr, Xv, yv, Xte, yte, last_closes_test, scaler = _sector_split_again(sector)

        # Predict in processed (normalized) space
        y_pred_norm = model.predict(Xte, verbose=0).reshape(-1)
        y_true_norm = yte.reshape(-1)

        # Processed (normalized returns) plots — paper Fig. 9 analogue
        base = f"{model_type}_{sector.replace(' ', '_')}"
        _plot_processed_returns(y_true_norm, y_pred_norm, f"{model_type} | {sector}", base)

        # Convert to real return units and reconstruct raw price — paper Figs. 10–13 analogue
        y_pred_ret = _invert_close_only(scaler, y_pred_norm)
        y_true_ret = _invert_close_only(scaler, y_true_norm)
        pred_px = last_closes_test + y_pred_ret
        true_px = last_closes_test + y_true_ret

        _plot_raw_prices(true_px, pred_px, f"{model_type} | {sector}", base)

        # (Optional) price metrics for quick console feedback
        rmse = np.sqrt(mean_squared_error(true_px, pred_px))
        mae  = mean_absolute_error(true_px, pred_px)
        print(f"[Block11] {model_type} | {sector}: price RMSE={rmse:.6f} MAE={mae:.6f}")

print(f"\nBlock 11 done. Paper-style figures saved under: {PAPER_FIG_DIR}")

[Block11] Transformer | Engineering: price RMSE=0.847842 MAE=0.526014
[Block11] Transformer | Fuel & Power: price RMSE=1.488694 MAE=1.228299
[Block11] Transformer | IT Sector: price RMSE=0.330997 MAE=0.208024
[Block11] Transformer | Services & Real Estate: price RMSE=0.526775 MAE=0.360958
[Block11] Transformer | Telecommunication: price RMSE=1.196357 MAE=0.694014
[Block11] LSTM | Engineering: price RMSE=0.770392 MAE=0.491081
[Block11] LSTM | Fuel & Power: price RMSE=1.571247 MAE=1.247905
[Block11] LSTM | IT Sector: price RMSE=0.279854 MAE=0.206141
[Block11] LSTM | Services & Real Estate: price RMSE=0.450916 MAE=0.321860
[Block11] LSTM | Telecommunication: price RMSE=1.129828 MAE=0.572693
[Block11] RNN | Engineering: price RMSE=0.819720 MAE=0.520160
[Block11] RNN | Fuel & Power: price RMSE=1.326326 MAE=1.069052
[Block11] RNN | IT Sector: price RMSE=0.284075 MAE=0.182168
[Block11] RNN | Services & Real Estate: price RMSE=1.112495 MAE=0.844186
[Block11] RNN | Telecommunication: price RMSE=1.101385 MAE=0.537762

Block 11 done. Paper-style figures saved under: /content/drive/MyDrive/AML /All/figures/paper_style

# Result Analysis